<a href="https://colab.research.google.com/github/Anavillag/Business-Analytics/blob/main/1_1_NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Modelo Niave Bayes - Preaprobación Creditos**
0. Cargar las librerias de trabajo

In [ ]:
import numpy as np #Funciones matemáticas
import pandas as pd #Conexión con archivos de excel

from sklearn.naive_bayes import GaussianNB #Modelo Gaussian Naive Bayes
from sklearn.metrics import confusion_matrix #Metricas- Como lo voy a evaluar


1. Se procede con la carga de los datos

In [ ]:
nxl='/content/0. SolicitantesCrédito(USD)_NAIVE BAYES  M.xlsx'
XDB=pd.read_excel(nxl, sheet_name=1)
XDB.dropna() #Para evitar celdas vacias
XDB.head(100)

#Creamos el DataMart
XD=XDB [['Edad','Ingresos','Egresos','Cuota (COP)']] #Variables Entrada
yd=XDB[['PreApr']] #Valor Deseado Aprenda el Modelo

2. Se procede con la configuración y evaluación del modelo Naive BAyes (PreAprob)


In [ ]:
from re import X
from functools import cmp_to_key
mnb=GaussianNB()
mnb.fit(XD,yd)

#Analizamos los resultados arrojados por el modelo
u=mnb.theta_  #Son las medias
print("Las medias de las variables son:\n", u)
sigma=np.sqrt(mnb.var_)
print("Los valores de las desviaciones son:\n",sigma)

#Se procede con el análisis de las variacioens de las variables
LS=u+sigma
print("Los limites superiores para las variables son:\n",LS)
LI=u-sigma
print("Los limites inferiores para las variables son:\n",LI)

#Se procede con la evaluación del comportamiento del modelo
#Prediciendo los valores de preaprobación del valor deseado
ydp=mnb.predict(XD) #Hizo el pronóstico de la Preaprobación para los solicitantes

cm=confusion_matrix(yd,ydp)
print("La matriz de confusión es:\n",cm)
VN=cm[0,0];FP=cm[0,1];FN=cm[1,0];VP=cm[1,1]

#Exactitud
Ex=(VP+VN)/len(XD)
print("La exactitud del modelo es:\n",Ex)

#Tasa de Error
Ter=(FP+FN)/len(XD)
print("La tasa de error del modelo es:\n",Ter)

#Sensibilidad
Sen=VP/(VP+FN)
print("La sensibilidad del modelo es:\n",Sen)

#Especificidad
Esp=VN/(VN+FN)
print("La especificidad del modelo es:\n",Esp)

#Precisión
Pres=VP/(VP+FP)
print("La precisión del modelo es:\n",Pres)

#Predicción Negativo
PredNeg=VN/(VN+FN)
print("La predicción negativa del modelo es:\n",PredNeg)

#Predicción Positivo
PredPos=VP/(VP+FP)
print("La predicción positiva del modelo es:\n",PredPos)

#Para evlauar solicitante de credito
XSC=[[37,517,629,10]]
ydsc=mnb.predict(XSC)
print("La predicción si una persona tendra un accidente automovilistico es:\n",ydsc)


Las medias de las variables son:
 [[  40.98411626  431.42680644  401.54995644   16.88529983]
 [  41.10752688 1029.98947251  900.19312144   43.3269839 ]]
Los valores de las desviaciones son:
 [[ 12.21303268 325.79791497 342.77286087  29.76942752]
 [ 12.25106493 472.43342807 525.43337837  64.98135094]]
Los limites superiores para las variables son:
 [[  53.19714893  757.22472141  744.32281731   46.65472735]
 [  53.35859181 1502.42290058 1425.62649981  108.30833484]]
Los limites inferiores para las variables son:
 [[ 28.77108358 105.62889147  58.77709557 -12.88412769]
 [ 28.85646196 557.55604444 374.75974307 -21.65436704]]
La matriz de confusión es:
 [[2563  396]
 [1192 1691]]
La exactitud del modelo es:
 0.7281752824375214
La tasa de error del modelo es:
 0.2718247175624786
La sensibilidad del modelo es:
 0.5865417967395075
La especificidad del modelo es:
 0.6825565912117177
La precisión del modelo es:
 0.8102539530426449
La predicción negativa del modelo es:
 0.6825565912117177
La predi

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


3. Se procede con la estimación de la preaprobación para los solicitantes nuevos

In [ ]:
XDBn=pd.read_excel(nxl, sheet_name=0)
XDBn.dropna() #Para evitar celdas vacias
XDBn.head(100)

#Creamos el DataMart
XDn=XDBn [['Edad','Ingresos','Egresos','Cuota (COP)']] #Variables Entrada
ydn=XDBn[['PreApr']] #Valor Deseado Aprenda el Modelo

#Hacer el pronostico para todos los datos posibles
ydpn=mnb.predict(XDn) #Hizo el pronóstico de la Preaprobación para los solicitantes

#Hacer el pronostico para todos los dtaos disponibles
ydpn=mnb.predict(XDn)

#Se procede con la creación del informe
XDsal=np.column_stack((XDn,ydpn,ydn)) #Para mostrar columnas
df_sal=pd.DataFrame (XDsal) #Se crea una tabla
df_sal.to_excel("Informe.xlsx")#Se envia al excel



**Análisis de Resultados**

Los resultados por el modelo propuesto frente al pronóstico de la PreAprobación, mostró que la precisión alvanzó un porcentaje del 72% lo que indica que de un total de 100 solicitantes de crédito el modelo tienda a equivocarse en 28 solicitudes de crédito. Según la métrica de sensibilidad la cual alcanzó valor 58% frente a la aprobación y una especificidad del 86% frente a la prenegación de créditos, lo que muestra que el modelo funciona mejor para PreNegar créditos que para PreAprobarlos. Es importante para tener en cuenta que el modelo arroja un informe de resultados en donde se evalua la PreAprobación para la totalidad de los solicitantes de crédito, tanto los activos como los nuevos solicitantes. Como información adicional la base de datos es posee un total de 2883 solicitantes de creditos PreAprobados y un total de 2959 solicitantes de crédito PreNegados.
