<a href="https://colab.research.google.com/github/Anavillag/Business-Analytics/blob/main/1_2_Reto_1_Modelo_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Reto 1 - Naive Bayes**

0. Cargar las librerias de trabajo


In [ ]:
import numpy as np  #Funciones matematicas
import pandas as pd #Conexiones conarchivos de excel

from sklearn.naive_bayes import GaussianNB #Modelo Gaussian Naive Bayes
from sklearn.metrics import confusion_matrix #Metricas- Como lo voy a evaluar



1. Se procede con la carga de los datos

In [ ]:
nxl='/content/1. BD2_CarCrash_Int.xlsx'
XDB= pd.read_excel(nxl, sheet_name=0)
XDB
XDB=XDB.dropna() #Función para evitar celdas vacias


#Se crea el DataMart
XD=XDB [['Weekday', 'ViolCat','ClearWeather','Month','Daylight']]
XD
yd=XDB [['Highway']] #Valor Deseado
yd

conteo=yd.value_counts()
porcentaje_categorias=(conteo/len(XD))*100
print(porcentaje_categorias)

Highway
0          100.0
Name: count, dtype: float64


2. Se procede con la configuración y evaluación del modelo Naive Bayes (Autopista/Highways)


In [ ]:
from re import X
from functools import cmp_to_key
mnb=GaussianNB()
mnb.fit(XD,yd)

#Analizamos los resultados arrojados por el modelo
u=mnb.theta_  #Son las medias
print("Las medias de las variables son:\n", u)
sigma=np.sqrt(mnb.var_)
print("Los valores de las desviaciones son:\n",sigma)

#Se procede con el análisis de las variacioens de las variables
LS=u+sigma
print("Los limites superiores para las variables son:\n",LS)
LI=u-sigma
print("Los limites inferiores para las variables son:\n",LI)

#Se procede con la evaluación del comportamiento del modelo
#Prediciendo los valores de preaprobación del valor deseado
ydp=mnb.predict(XD) #Hizo el pronóstico de la Preaprobación para los solicitantes

cm=confusion_matrix(yd,ydp)
print("La matriz de confusión es:\n",cm)
VN=cm[0,0]
FP=cm[0,1]
FN=cm[1,0]
VP=cm[1,1]
print("VN=",VN)
print("FP=",FP)
print("FN=",FN)
print("VP=",VP)

#Exactitud
Ex=(VP+VN)/len(XD)
print("La exactitud del modelo es:\n",Ex)

#Tasa de Error
Ter=(FP+FN)/len(XD)
print("La tasa de error del modelo es:\n",Ter)

#Sensibilidad
Sen=VP/(VP+FP)
print("La sensibilidad del modelo es:\n",Sen)

#Especificidad
Esp=VN/(VN+FP)
print("La especificidad del modelo es:\n",Esp)

#Precisión
Pres=VP/(VP+FP)
print("La precisión del modelo es:\n",Pres)

#Predicción Negativo
PredNeg=VN/(VN+FN)
print("La predicción negativa del modelo es:\n",PredNeg)

#Predicción Positivo
PredPos=VP/(VP+FP)
print("La predicción positiva del modelo es:\n",PredPos)

#Para evlauar solicitante de credito
XSC=[[7,1,1,3,0]]
ydsc=mnb.predict(XSC)
print("La predicción si una persona tendra un accidente automovilistico es:\n",ydsc)


Las medias de las variables son:
 [[3.90307801 6.79464607 0.89238754 6.67500217 0.69460758]
 [3.92883161 4.45913888 0.86345382 6.68867719 0.69487251]]
Los valores de las desviaciones son:
 [[1.93312956 3.60184338 0.30989035 3.36048976 0.46057345]
 [1.91313258 2.47514729 0.34336764 3.33713602 0.46046142]]
Los limites superiores para las variables son:
 [[ 5.83620757 10.39648945  1.20227789 10.03549193  1.15518103]
 [ 5.84196418  6.93428617  1.20682146 10.02581321  1.15533393]]
Los limites inferiores para las variables son:
 [[1.96994846 3.1928027  0.58249719 3.31451241 0.23403413]
 [2.01569903 1.98399159 0.52008618 3.35154117 0.2344111 ]]
La matriz de confusión es:
 [[76765  3774]
 [29191  2930]]
VN= 76765
FP= 3774
FN= 29191
VP= 2930
La exactitud del modelo es:
 0.7073939286348304
La tasa de error del modelo es:
 0.29260607136516953
La sensibilidad del modelo es:
 0.4370525059665871
La especificidad del modelo es:
 0.9531407144364842
La precisión del modelo es:
 0.4370525059665871
La pr

3. Estimación

In [ ]:

XDBn=pd.read_excel(nxl, sheet_name=0)
XDBn.dropna() #Para evitar celdas vacias
XDBn.head(100)

#Creamos el DataMart
XDn=XDBn [['Weekday', 'ViolCat','ClearWeather','Month','Daylight']] #Variables Entrada
ydn=XDBn[['Highway']] #Valor Deseado Aprenda el Modelo

#Hacer el pronostico para todos los datos posibles
ydpn=mnb.predict(XDn) #Hizo el pronóstico de la Preaprobación para los solicitantes

#Hacer el pronostico para todos los dtaos disponibles
ydpn=mnb.predict(XDn)

#Se procede con la creación del informe
XDsal=np.column_stack((XDn,ydpn,ydn)) #Para mostrar columnas
df_sal=pd.DataFrame (XDsal) #Se crea una tabla
df_sal.to_excel("Informe.xlsx")#Se envia al excel

NameError: name 'pd' is not defined